-- =============================================================================
-- V1 :: Baseline Schema - PostgreSQL
-- Consolidated baseline for VFAR competence matching.
-- Contains only active consultant-platform, runtime, and audit persistence.
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS consultant_platform;
CREATE SCHEMA IF NOT EXISTS runtime;

-- -------------------------------------------------------------------------
-- consultant_platform.competency_level_lookup
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS consultant_platform.competency_level_lookup (
    competency_level_lookup_id SMALLINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    competency_level_name      VARCHAR(20) NOT NULL,
    competency_min_years       SMALLINT    NOT NULL,
    PRIMARY KEY (competency_level_lookup_id),
    CONSTRAINT uk_competency_level_lookup_name UNIQUE (competency_level_name),
    CONSTRAINT uk_competency_level_lookup_min_years UNIQUE (competency_min_years),
    CONSTRAINT chk_competency_level_lookup_name_nonblank CHECK (CHAR_LENGTH(TRIM(competency_level_name)) > 0),
    CONSTRAINT chk_competency_level_lookup_min_years CHECK (competency_min_years >= 0)
);

-- -------------------------------------------------------------------------
-- consultant_platform.role
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS consultant_platform.role (
    role_id    BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    role_title VARCHAR(100) NOT NULL,
    PRIMARY KEY (role_id),
    CONSTRAINT uk_role_title           UNIQUE (role_title),
    CONSTRAINT chk_role_title_nonblank CHECK  (CHAR_LENGTH(TRIM(role_title)) > 0)
);

-- consultant_platform.skills_primary
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS consultant_platform.skills_primary (
    primary_skill_id BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    skill_title      VARCHAR(150) NOT NULL,
    PRIMARY KEY (primary_skill_id),
    CONSTRAINT uk_skills_primary_title UNIQUE (skill_title),
    CONSTRAINT chk_skills_primary_title_nonblank CHECK (CHAR_LENGTH(TRIM(skill_title)) > 0)
);

-- -------------------------------------------------------------------------
-- consultant_platform.skills_secondary
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS consultant_platform.skills_secondary (
    secondary_skill_id BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    skill_title        VARCHAR(150) NOT NULL,
    PRIMARY KEY (secondary_skill_id),
    CONSTRAINT uk_skills_secondary_title UNIQUE (skill_title),
    CONSTRAINT chk_skills_secondary_title_nonblank CHECK (CHAR_LENGTH(TRIM(skill_title)) > 0)
);

-- -------------------------------------------------------------------------
-- consultant_platform.customer
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS consultant_platform.customer (
    customer_id    BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    customer_name  VARCHAR(200) NOT NULL,
    customer_email VARCHAR(150) NOT NULL,
    PRIMARY KEY (customer_id),
    CONSTRAINT chk_customer_name_nonblank CHECK (CHAR_LENGTH(TRIM(customer_name)) > 0),
    CONSTRAINT chk_customer_email_has_at CHECK (customer_email LIKE '%@%'),
    CONSTRAINT uk_customer_name_email UNIQUE (customer_name, customer_email)
);

-- -------------------------------------------------------------------------
-- consultant_platform.company_identity_lookup
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS consultant_platform.company_identity_lookup (
    company_identity_lookup_id   BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    organisation_number          VARCHAR(30)  NOT NULL,
    organisation_name            VARCHAR(200) NOT NULL,
    organisation_name_normalized VARCHAR(200) NOT NULL,
    organisation_city            VARCHAR(100),
    source                       VARCHAR(40)  NOT NULL DEFAULT 'SCB',
    imported_at                  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (company_identity_lookup_id),
    CONSTRAINT uk_company_identity_lookup_org_nr UNIQUE (organisation_number),
    CONSTRAINT chk_company_identity_org_nr_nonblank CHECK (CHAR_LENGTH(TRIM(organisation_number)) > 0),
    CONSTRAINT chk_company_identity_name_nonblank CHECK (CHAR_LENGTH(TRIM(organisation_name)) > 0),
    CONSTRAINT chk_company_identity_name_norm_nonblank CHECK (CHAR_LENGTH(TRIM(organisation_name_normalized)) > 0)
);

CREATE INDEX IF NOT EXISTS idx_company_identity_lookup_name_norm
    ON consultant_platform.company_identity_lookup (organisation_name_normalized);

-- -------------------------------------------------------------------------
-- consultant_platform.cand_appli
-- Frozen original/audit snapshot. Not a matching head model.
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS consultant_platform.cand_appli (
    cand_appli_id            BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    submission_snapshot_json TEXT        NOT NULL,
    created_at               TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (cand_appli_id),
    CONSTRAINT chk_cand_appli_snapshot_nonblank CHECK (CHAR_LENGTH(TRIM(submission_snapshot_json)) > 0)
);

CREATE INDEX IF NOT EXISTS idx_cand_appli_created_at
    ON consultant_platform.cand_appli (created_at);

-- -------------------------------------------------------------------------
-- consultant_platform.cand_profile
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS consultant_platform.cand_profile (
    cand_profile_id BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    contact_email                    VARCHAR(150) NOT NULL,
    candidate_first_name             VARCHAR(100) NOT NULL DEFAULT '',
    candidate_last_name              VARCHAR(100) NOT NULL DEFAULT '',
    candidate_phone_number           VARCHAR(100) NOT NULL DEFAULT '',
    candidate_country                VARCHAR(100) NOT NULL DEFAULT '',
    candidate_city                   VARCHAR(100) NOT NULL DEFAULT '',
    candidate_work_status            TEXT         NOT NULL DEFAULT '',
    candidate_languages              TEXT         NOT NULL DEFAULT '',
    cand_role_title                  VARCHAR(150) NOT NULL DEFAULT '',
    candidate_profile_summary        TEXT         NOT NULL DEFAULT '',
    candidate_years_of_experience    VARCHAR(20)  NOT NULL DEFAULT '',
    candidate_expected_salary        VARCHAR(50)  NOT NULL DEFAULT '',
    candidate_hourly_rate            VARCHAR(50)  NOT NULL DEFAULT '',
    cand_skills                      TEXT         NOT NULL DEFAULT '',
    candidate_work_mode              VARCHAR(50)  NOT NULL DEFAULT '',
    candidate_location_flexibility   VARCHAR(100) NOT NULL DEFAULT '',
    candidate_preferred_location     VARCHAR(150) NOT NULL DEFAULT '',
    candidate_willing_to_relocate    BOOLEAN      NOT NULL DEFAULT FALSE,
    candidate_gdpr_consent           BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at                       TIMESTAMPTZ  NOT NULL,
    updated_at                       TIMESTAMPTZ  NOT NULL,
    PRIMARY KEY (cand_profile_id),
    CONSTRAINT chk_cand_profile_email_has_at CHECK (contact_email LIKE '%@%')
);

CREATE INDEX IF NOT EXISTS idx_cand_profile_created_at
    ON consultant_platform.cand_profile (created_at);

-- -------------------------------------------------------------------------
-- consultant_platform.cand_profile_cv
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS consultant_platform.cand_profile_cv (
    cand_profile_cv_id       BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    cand_profile_id          BIGINT       NOT NULL,
    cv_file_name             VARCHAR(255) NOT NULL,
    cv_content_type          VARCHAR(100) NOT NULL,
    cv_size_bytes            BIGINT       NULL,
    cv_extraction_pending    BOOLEAN      NOT NULL DEFAULT TRUE,
    cv_extraction_status     VARCHAR(40)  NOT NULL DEFAULT 'METADATA_ONLY',
    cv_extracted_text        TEXT         NOT NULL DEFAULT '',
    cv_extraction_error      TEXT         NOT NULL DEFAULT '',
    cv_extracted_at          TIMESTAMPTZ  NULL,
    cv_summary_status        VARCHAR(20)  NOT NULL DEFAULT 'NOT_GENERATED',
    cv_summary_core_competence_overview TEXT NOT NULL DEFAULT '',
    cv_summary_location      TEXT         NOT NULL DEFAULT '',
    cv_summary_other_details TEXT         NOT NULL DEFAULT '',
    cv_summary_generated_at  TIMESTAMPTZ  NULL,
    PRIMARY KEY (cand_profile_cv_id),
    CONSTRAINT uq_cand_profile_cv_profile UNIQUE (cand_profile_id),
    CONSTRAINT chk_cand_profile_cv_size CHECK (cv_size_bytes IS NULL OR cv_size_bytes >= 0),
    CONSTRAINT chk_cand_profile_cv_extraction_status CHECK (cv_extraction_status IN ('METADATA_ONLY', 'EXTRACTED', 'EMPTY_TEXT', 'UNSUPPORTED_CONTENT_TYPE', 'FAILED')),
    CONSTRAINT chk_cand_profile_cv_summary_status CHECK (cv_summary_status IN ('NOT_GENERATED', 'GENERATED', 'STALE')),
    CONSTRAINT fk_cand_profile_cv_profile FOREIGN KEY (cand_profile_id) REFERENCES consultant_platform.cand_profile (cand_profile_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_cand_profile_cv_profile_id
    ON consultant_platform.cand_profile_cv (cand_profile_id);

CREATE INDEX IF NOT EXISTS idx_cand_profile_cv_extraction_status
    ON consultant_platform.cand_profile_cv (cv_extraction_status);

-- -------------------------------------------------------------------------
-- consultant_platform.cand_profile_roles
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS consultant_platform.cand_profile_roles (
    cand_profile_role_id    BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    cand_profile_id         BIGINT       NOT NULL,
    role_number             INT          NOT NULL,
    role_id                 BIGINT       NOT NULL,
    role_title              VARCHAR(150) NOT NULL DEFAULT '',
    role_experience_years   SMALLINT     NOT NULL DEFAULT 0,
    competency_level_id     SMALLINT     NOT NULL DEFAULT 1,
    PRIMARY KEY (cand_profile_role_id),
    CONSTRAINT uq_cand_profile_role_number UNIQUE (cand_profile_id, role_number),
    CONSTRAINT uq_cand_profile_role_id UNIQUE (cand_profile_id, role_id),
    CONSTRAINT chk_cand_profile_role_number CHECK (role_number >= 1),
    CONSTRAINT chk_cand_profile_role_title CHECK (CHAR_LENGTH(TRIM(role_title)) > 0),
    CONSTRAINT chk_cand_profile_role_experience_years CHECK (role_experience_years >= 0),
    CONSTRAINT fk_cand_profile_role_competency_level FOREIGN KEY (competency_level_id) REFERENCES consultant_platform.competency_level_lookup (competency_level_lookup_id),
    CONSTRAINT fk_cand_profile_role_profile FOREIGN KEY (cand_profile_id) REFERENCES consultant_platform.cand_profile (cand_profile_id) ON DELETE CASCADE,
    CONSTRAINT fk_cand_profile_role_role FOREIGN KEY (role_id) REFERENCES consultant_platform.role (role_id)
);

CREATE INDEX IF NOT EXISTS idx_cand_profile_roles_profile_id
    ON consultant_platform.cand_profile_roles (cand_profile_id);

CREATE INDEX IF NOT EXISTS idx_cand_profile_roles_role_id
    ON consultant_platform.cand_profile_roles (role_id);

-- -------------------------------------------------------------------------
-- consultant_platform.cand_profile_skills_primary
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS consultant_platform.cand_profile_skills_primary (
    cand_profile_primary_skill_id BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    cand_profile_id               BIGINT       NOT NULL,
    skill_number                  INT          NOT NULL,
    primary_skill_id              BIGINT       NOT NULL,
    skill_title                   VARCHAR(150) NOT NULL DEFAULT '',
    competency_level_id           SMALLINT     NOT NULL,
    PRIMARY KEY (cand_profile_primary_skill_id),
    CONSTRAINT uq_cand_profile_primary_skill_number UNIQUE (cand_profile_id, skill_number),
    CONSTRAINT uq_cand_profile_primary_skill_id UNIQUE (cand_profile_id, primary_skill_id),
    CONSTRAINT chk_cand_profile_primary_skill_number CHECK (skill_number >= 1),
    CONSTRAINT chk_cand_profile_primary_skill_title CHECK (CHAR_LENGTH(TRIM(skill_title)) > 0),
    CONSTRAINT fk_cand_profile_primary_skill_profile FOREIGN KEY (cand_profile_id) REFERENCES consultant_platform.cand_profile (cand_profile_id) ON DELETE CASCADE,
    CONSTRAINT fk_cand_profile_primary_skill_skill FOREIGN KEY (primary_skill_id) REFERENCES consultant_platform.skills_primary (primary_skill_id),
    CONSTRAINT fk_cand_profile_primary_skill_competency_level FOREIGN KEY (competency_level_id) REFERENCES consultant_platform.competency_level_lookup (competency_level_lookup_id)
);

CREATE INDEX IF NOT EXISTS idx_cand_profile_skills_primary_profile_id
    ON consultant_platform.cand_profile_skills_primary (cand_profile_id);

CREATE INDEX IF NOT EXISTS idx_cand_profile_skills_primary_skill_id
    ON consultant_platform.cand_profile_skills_primary (primary_skill_id);

-- -------------------------------------------------------------------------
-- consultant_platform.cand_profile_skills_secondary
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS consultant_platform.cand_profile_skills_secondary (
    cand_profile_secondary_skill_id BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    cand_profile_id                 BIGINT       NOT NULL,
    skill_number                    INT          NOT NULL,
    secondary_skill_id              BIGINT       NOT NULL,
    skill_title                     VARCHAR(150) NOT NULL DEFAULT '',
    competency_level_id             SMALLINT     NOT NULL,
    PRIMARY KEY (cand_profile_secondary_skill_id),
    CONSTRAINT uq_cand_profile_secondary_skill_number UNIQUE (cand_profile_id, skill_number),
    CONSTRAINT uq_cand_profile_secondary_skill_id UNIQUE (cand_profile_id, secondary_skill_id),
    CONSTRAINT chk_cand_profile_secondary_skill_number CHECK (skill_number >= 1),
    CONSTRAINT chk_cand_profile_secondary_skill_title CHECK (CHAR_LENGTH(TRIM(skill_title)) > 0),
    CONSTRAINT fk_cand_profile_secondary_skill_profile FOREIGN KEY (cand_profile_id) REFERENCES consultant_platform.cand_profile (cand_profile_id) ON DELETE CASCADE,
    CONSTRAINT fk_cand_profile_secondary_skill_skill FOREIGN KEY (secondary_skill_id) REFERENCES consultant_platform.skills_secondary (secondary_skill_id),
    CONSTRAINT fk_cand_profile_secondary_skill_competency_level FOREIGN KEY (competency_level_id) REFERENCES consultant_platform.competency_level_lookup (competency_level_lookup_id)
);

CREATE INDEX IF NOT EXISTS idx_cand_profile_skills_secondary_profile_id
    ON consultant_platform.cand_profile_skills_secondary (cand_profile_id);

CREATE INDEX IF NOT EXISTS idx_cand_profile_skills_secondary_skill_id
    ON consultant_platform.cand_profile_skills_secondary (secondary_skill_id);


-- consultant_platform.cand_profile_certifications
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS consultant_platform.cand_profile_certifications (
    cand_profile_certification_id BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    cand_profile_id               BIGINT       NOT NULL,
    certification_number          INT          NOT NULL,
    certification_name            VARCHAR(150) NOT NULL DEFAULT '',
    document_file_name            VARCHAR(255) NOT NULL DEFAULT '',
    document_content_type         VARCHAR(120) NOT NULL DEFAULT '',
    document_size_bytes           BIGINT       NULL,
    document_bytes                BYTEA        NULL,
    document_uploaded_at          TIMESTAMPTZ  NULL,
    PRIMARY KEY (cand_profile_certification_id),
    CONSTRAINT uk_cand_profile_certification UNIQUE (cand_profile_id, certification_number),
    CONSTRAINT chk_cand_profile_certification_number CHECK (certification_number >= 1),
    CONSTRAINT chk_cand_profile_certification_doc_size CHECK (document_size_bytes IS NULL OR document_size_bytes >= 0),
    CONSTRAINT fk_cand_profile_certification_profile FOREIGN KEY (cand_profile_id) REFERENCES consultant_platform.cand_profile (cand_profile_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_cand_profile_certifications_profile_id
    ON consultant_platform.cand_profile_certifications (cand_profile_id);

-- -------------------------------------------------------------------------
-- consultant_platform.cand_profile_work_experiences
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS consultant_platform.cand_profile_work_experiences (
    cand_profile_work_experience_id BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    cand_profile_id                 BIGINT       NOT NULL,
    work_experience_number          INT          NOT NULL,
    job_title                       VARCHAR(150) NOT NULL DEFAULT '',
    work_exp_company                VARCHAR(200) NOT NULL DEFAULT '',
    work_exp_company_org_nr         VARCHAR(30)  NOT NULL DEFAULT '',
    city                            VARCHAR(100) NOT NULL DEFAULT '',
    country                         VARCHAR(100) NOT NULL DEFAULT '',
    start_date                      DATE         NULL,
    end_date                        DATE         NULL,
    currently_here                  BOOLEAN      NOT NULL DEFAULT FALSE,
    PRIMARY KEY (cand_profile_work_experience_id),
    CONSTRAINT uk_cand_profile_work_experience UNIQUE (cand_profile_id, work_experience_number),
    CONSTRAINT chk_cand_profile_work_experience_number CHECK (work_experience_number >= 1),
    CONSTRAINT chk_cand_profile_work_experience_dates CHECK (start_date IS NULL OR end_date IS NULL OR start_date <= end_date),
    CONSTRAINT fk_cand_profile_work_experience_profile FOREIGN KEY (cand_profile_id) REFERENCES consultant_platform.cand_profile (cand_profile_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_cand_profile_work_experiences_profile_id
    ON consultant_platform.cand_profile_work_experiences (cand_profile_id);

-- -------------------------------------------------------------------------
-- consultant_platform.cand_profile_educations
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS consultant_platform.cand_profile_educations (
    cand_profile_education_id BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    cand_profile_id           BIGINT       NOT NULL,
    education_number          INT          NOT NULL,
    institution               VARCHAR(150) NOT NULL DEFAULT '',
    field_of_study            VARCHAR(150) NOT NULL DEFAULT '',
    start_date                DATE         NULL,
    end_date                  DATE         NULL,
    currently_studying        BOOLEAN      NOT NULL DEFAULT FALSE,
    PRIMARY KEY (cand_profile_education_id),
    CONSTRAINT uk_cand_profile_education UNIQUE (cand_profile_id, education_number),
    CONSTRAINT chk_cand_profile_education_number CHECK (education_number >= 1),
    CONSTRAINT chk_cand_profile_education_dates CHECK (start_date IS NULL OR end_date IS NULL OR start_date <= end_date),
    CONSTRAINT fk_cand_profile_education_profile FOREIGN KEY (cand_profile_id) REFERENCES consultant_platform.cand_profile (cand_profile_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_cand_profile_educations_profile_id
    ON consultant_platform.cand_profile_educations (cand_profile_id);

-- -------------------------------------------------------------------------
-- consultant_platform.mission
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS consultant_platform.mission (
    mission_id                  BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    source_mission_proposal_id  BIGINT       NULL,
    customer_id                      BIGINT       NOT NULL,
    customer_name                    VARCHAR(200) NOT NULL,
    customer_email                   VARCHAR(150) NOT NULL,
    mission_title                    VARCHAR(200) NOT NULL,
    mission_start_date               DATE         NOT NULL,
    mission_end_date                 DATE         NOT NULL,
    work_mode                        VARCHAR(20)  NOT NULL,
    presentation_one_day_at_work             TEXT         NOT NULL DEFAULT '',
    presentation_technical_landscape         TEXT         NOT NULL DEFAULT '',
    presentation_who_we_are_looking_for      TEXT         NOT NULL DEFAULT '',
    presentation_what_we_offer               TEXT         NOT NULL DEFAULT '',
    presentation_about_customer               TEXT         NOT NULL DEFAULT '',
    presentation_recruitment_process         TEXT         NOT NULL DEFAULT '',
    mission_availability             VARCHAR(10)  NOT NULL DEFAULT 'OPEN',
    PRIMARY KEY (mission_id),
    CONSTRAINT uk_mission_source_proposal UNIQUE (source_mission_proposal_id),
    CONSTRAINT chk_mission_customer_name_nonblank CHECK (CHAR_LENGTH(TRIM(customer_name)) > 0),
    CONSTRAINT chk_mission_email_has_at CHECK (customer_email LIKE '%@%'),
    CONSTRAINT chk_mission_title_nonblank CHECK (CHAR_LENGTH(TRIM(mission_title)) > 0),
    CONSTRAINT chk_mission_dates CHECK (mission_start_date <= mission_end_date),
    CONSTRAINT chk_mission_work_mode CHECK (work_mode IN ('ON_PREMISE', 'REMOTE', 'HYBRID')),
    CONSTRAINT chk_mission_availability CHECK (mission_availability IN ('OPEN', 'CLOSED')),
    CONSTRAINT fk_mission_customer FOREIGN KEY (customer_id) REFERENCES consultant_platform.customer (customer_id)
);

CREATE INDEX IF NOT EXISTS idx_mission_customer_id
    ON consultant_platform.mission (customer_id);

CREATE INDEX IF NOT EXISTS idx_mission_availability
    ON consultant_platform.mission (mission_availability);

-- -------------------------------------------------------------------------
-- consultant_platform.mission_slot
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS consultant_platform.mission_slot (
    mission_slot_id               BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    mission_id                    BIGINT      NOT NULL,
    role_id                            BIGINT      NOT NULL,
    required_role_experience_years     SMALLINT    NOT NULL DEFAULT 2,
    req_competency_level_id            SMALLINT    NOT NULL DEFAULT 2,
    mission_slot_number                INT         NOT NULL DEFAULT 1,
    mission_slot_fill_status           VARCHAR(20) NOT NULL DEFAULT 'NOT_FILLED',
    mission_slot_filled_by_profile_id  BIGINT      NULL,
    mission_slot_filled_at             TIMESTAMPTZ NULL,
    PRIMARY KEY (mission_slot_id),
    CONSTRAINT uk_mission_slot_number UNIQUE (mission_id, mission_slot_number),
    CONSTRAINT chk_mission_slot_number_positive CHECK (mission_slot_number >= 1),
    CONSTRAINT chk_mission_slot_required_role_experience_years CHECK (required_role_experience_years >= 0),
    CONSTRAINT fk_mission_slot_req_competency_level FOREIGN KEY (req_competency_level_id) REFERENCES consultant_platform.competency_level_lookup (competency_level_lookup_id),
    CONSTRAINT chk_mission_slot_fill_status CHECK (mission_slot_fill_status IN ('NOT_FILLED', 'FILLED')),
    CONSTRAINT chk_mission_slot_fill_state_consistency CHECK (
        (mission_slot_fill_status = 'NOT_FILLED'
            AND mission_slot_filled_by_profile_id IS NULL
            AND mission_slot_filled_at IS NULL)
        OR
        (mission_slot_fill_status = 'FILLED'
            AND mission_slot_filled_by_profile_id IS NOT NULL
            AND mission_slot_filled_at IS NOT NULL)
    ),
    CONSTRAINT fk_mission_slot_mission FOREIGN KEY (mission_id) REFERENCES consultant_platform.mission (mission_id),
    CONSTRAINT fk_mission_slot_role FOREIGN KEY (role_id) REFERENCES consultant_platform.role (role_id),
    CONSTRAINT fk_mission_slot_filled_by_profile FOREIGN KEY (mission_slot_filled_by_profile_id) REFERENCES consultant_platform.cand_profile (cand_profile_id)
);

CREATE INDEX IF NOT EXISTS idx_mission_slot_mission_id
    ON consultant_platform.mission_slot (mission_id);

CREATE INDEX IF NOT EXISTS idx_mission_slot_role_fill_status
    ON consultant_platform.mission_slot (role_id, mission_slot_fill_status);

CREATE INDEX IF NOT EXISTS idx_mission_slot_filled_by_profile_id
    ON consultant_platform.mission_slot (mission_slot_filled_by_profile_id);

-- -------------------------------------------------------------------------
-- consultant_platform.mission_slot_required_skill
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS consultant_platform.mission_slot_required_skill (
    mission_slot_required_skill_id BIGINT   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    mission_slot_id                   BIGINT   NOT NULL,
    primary_skill_id                       BIGINT   NOT NULL,
    skill_title                            VARCHAR(150) NOT NULL DEFAULT '',
    req_competency_level_id                SMALLINT NOT NULL,
    PRIMARY KEY (mission_slot_required_skill_id),
    CONSTRAINT uk_mission_slot_required_skill UNIQUE (mission_slot_id, primary_skill_id),
    CONSTRAINT fk_mission_slot_required_skill_slot FOREIGN KEY (mission_slot_id) REFERENCES consultant_platform.mission_slot (mission_slot_id),
    CONSTRAINT fk_mission_slot_required_skill_skill FOREIGN KEY (primary_skill_id) REFERENCES consultant_platform.skills_primary (primary_skill_id),
    CONSTRAINT fk_mission_slot_required_skill_competency_level FOREIGN KEY (req_competency_level_id) REFERENCES consultant_platform.competency_level_lookup (competency_level_lookup_id)
);

CREATE INDEX IF NOT EXISTS idx_mission_slot_required_skill_slot_id
    ON consultant_platform.mission_slot_required_skill (mission_slot_id);

CREATE INDEX IF NOT EXISTS idx_mission_slot_required_skill_skill_id
    ON consultant_platform.mission_slot_required_skill (primary_skill_id);

-- -------------------------------------------------------------------------
-- consultant_platform.mission_slot_secondary_required_skill
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS consultant_platform.mission_slot_secondary_required_skill (
    mission_slot_secondary_required_skill_id BIGINT   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    mission_slot_id                     BIGINT   NOT NULL,
    secondary_skill_id                       BIGINT   NOT NULL,
    skill_title                              VARCHAR(150) NOT NULL DEFAULT '',
    req_competency_level_id                  SMALLINT NOT NULL,
    PRIMARY KEY (mission_slot_secondary_required_skill_id),
    CONSTRAINT uk_mission_slot_secondary_required_skill UNIQUE (mission_slot_id, secondary_skill_id),
    CONSTRAINT fk_mission_slot_secondary_required_skill_slot FOREIGN KEY (mission_slot_id) REFERENCES consultant_platform.mission_slot (mission_slot_id),
    CONSTRAINT fk_mission_slot_secondary_required_skill_skill FOREIGN KEY (secondary_skill_id) REFERENCES consultant_platform.skills_secondary (secondary_skill_id),
    CONSTRAINT fk_mission_slot_secondary_required_skill_competency_level FOREIGN KEY (req_competency_level_id) REFERENCES consultant_platform.competency_level_lookup (competency_level_lookup_id)
);

CREATE INDEX IF NOT EXISTS idx_mission_slot_secondary_required_skill_slot_id
    ON consultant_platform.mission_slot_secondary_required_skill (mission_slot_id);

CREATE INDEX IF NOT EXISTS idx_mission_slot_secondary_required_skill_skill_id
    ON consultant_platform.mission_slot_secondary_required_skill (secondary_skill_id);

-- -------------------------------------------------------------------------
-- consultant_platform.mission_proposal
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS consultant_platform.mission_proposal (
    mission_proposal_id    BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    customer_id                     BIGINT       NOT NULL,
    customer_name                   VARCHAR(200) NOT NULL,
    customer_email                  VARCHAR(150) NOT NULL,
    mission_title                   VARCHAR(200) NOT NULL,
    mission_start_date              DATE         NOT NULL,
    mission_end_date                DATE         NOT NULL,
    work_mode                       VARCHAR(20)  NOT NULL,
    presentation_one_day_at_work            TEXT         NOT NULL DEFAULT '',
    presentation_technical_landscape        TEXT         NOT NULL DEFAULT '',
    presentation_who_we_are_looking_for     TEXT         NOT NULL DEFAULT '',
    presentation_what_we_offer              TEXT         NOT NULL DEFAULT '',
    presentation_about_customer              TEXT         NOT NULL DEFAULT '',
    presentation_recruitment_process        TEXT         NOT NULL DEFAULT '',
    mission_proposal_review_status VARCHAR(20) NOT NULL DEFAULT 'SUBMITTED',
    created_at                      TIMESTAMPTZ  NOT NULL,
    updated_at                      TIMESTAMPTZ  NOT NULL,
    PRIMARY KEY (mission_proposal_id),
    CONSTRAINT chk_mission_proposal_customer_name_nonblank CHECK (CHAR_LENGTH(TRIM(customer_name)) > 0),
    CONSTRAINT chk_mission_proposal_email_has_at CHECK (customer_email LIKE '%@%'),
    CONSTRAINT chk_mission_proposal_title_nonblank CHECK (CHAR_LENGTH(TRIM(mission_title)) > 0),
    CONSTRAINT chk_mission_proposal_dates CHECK (mission_start_date <= mission_end_date),
    CONSTRAINT chk_mission_proposal_work_mode CHECK (work_mode IN ('ON_PREMISE', 'REMOTE', 'HYBRID')),
    CONSTRAINT chk_mission_proposal_status CHECK (mission_proposal_review_status IN ('SUBMITTED', 'IN_REVIEW', 'APPROVED', 'REJECTED')),
    CONSTRAINT fk_mission_proposal_customer FOREIGN KEY (customer_id) REFERENCES consultant_platform.customer (customer_id)
);

CREATE INDEX IF NOT EXISTS idx_mission_proposal_customer_id
    ON consultant_platform.mission_proposal (customer_id);

CREATE INDEX IF NOT EXISTS idx_mission_proposal_status
    ON consultant_platform.mission_proposal (mission_proposal_review_status);

CREATE INDEX IF NOT EXISTS idx_mission_proposal_created_at
    ON consultant_platform.mission_proposal (created_at);

-- -------------------------------------------------------------------------
-- consultant_platform.mission_proposal_slot
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS consultant_platform.mission_proposal_slot (
    mission_proposal_slot_id           BIGINT   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    mission_proposal_id                BIGINT   NOT NULL,
    mission_slot_number                         INT      NOT NULL,
    role_id                                     BIGINT   NOT NULL,
    required_role_experience_years             SMALLINT NOT NULL DEFAULT 0,
    req_competency_level_id                  SMALLINT NOT NULL DEFAULT 1,
    PRIMARY KEY (mission_proposal_slot_id),
    CONSTRAINT uk_mission_proposal_slot_number UNIQUE (mission_proposal_id, mission_slot_number),
    CONSTRAINT chk_mission_proposal_slot_number CHECK (mission_slot_number >= 1),
    CONSTRAINT chk_mission_proposal_slot_required_role_experience_years CHECK (required_role_experience_years >= 0),
    CONSTRAINT fk_mission_proposal_slot_req_competency_level FOREIGN KEY (req_competency_level_id) REFERENCES consultant_platform.competency_level_lookup (competency_level_lookup_id),
    CONSTRAINT fk_mission_proposal_slot_proposal FOREIGN KEY (mission_proposal_id) REFERENCES consultant_platform.mission_proposal (mission_proposal_id) ON DELETE CASCADE,
    CONSTRAINT fk_mission_proposal_slot_role FOREIGN KEY (role_id) REFERENCES consultant_platform.role (role_id)
);

CREATE INDEX IF NOT EXISTS idx_mission_proposal_slot_proposal_id
    ON consultant_platform.mission_proposal_slot (mission_proposal_id);

CREATE INDEX IF NOT EXISTS idx_mission_proposal_slot_role_id
    ON consultant_platform.mission_proposal_slot (role_id);

-- -------------------------------------------------------------------------
-- consultant_platform.mission_proposal_slot_required_skill
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS consultant_platform.mission_proposal_slot_required_skill (
    mission_proposal_slot_required_skill_id BIGINT   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    mission_proposal_slot_id                   BIGINT   NOT NULL,
    primary_skill_id                                BIGINT   NOT NULL,
    req_competency_level_id                         SMALLINT NOT NULL,
    PRIMARY KEY (mission_proposal_slot_required_skill_id),
    CONSTRAINT uk_mission_proposal_slot_required_skill UNIQUE (mission_proposal_slot_id, primary_skill_id),
    CONSTRAINT fk_mission_proposal_slot_required_skill_slot FOREIGN KEY (mission_proposal_slot_id) REFERENCES consultant_platform.mission_proposal_slot (mission_proposal_slot_id) ON DELETE CASCADE,
    CONSTRAINT fk_mission_proposal_slot_required_skill_skill FOREIGN KEY (primary_skill_id) REFERENCES consultant_platform.skills_primary (primary_skill_id),
    CONSTRAINT fk_mission_proposal_slot_required_skill_competency_level FOREIGN KEY (req_competency_level_id) REFERENCES consultant_platform.competency_level_lookup (competency_level_lookup_id)
);

CREATE INDEX IF NOT EXISTS idx_mission_proposal_slot_required_skill_slot_id
    ON consultant_platform.mission_proposal_slot_required_skill (mission_proposal_slot_id);

CREATE INDEX IF NOT EXISTS idx_mission_proposal_slot_required_skill_skill_id
    ON consultant_platform.mission_proposal_slot_required_skill (primary_skill_id);

-- -------------------------------------------------------------------------
-- consultant_platform.mission_proposal_slot_secondary_required_skill
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS consultant_platform.mission_proposal_slot_secondary_required_skill (
    mission_proposal_slot_secondary_required_skill_id BIGINT   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    mission_proposal_slot_id                     BIGINT   NOT NULL,
    secondary_skill_id                                BIGINT   NOT NULL,
    req_competency_level_id                           SMALLINT NOT NULL,
    PRIMARY KEY (mission_proposal_slot_secondary_required_skill_id),
    CONSTRAINT uk_mission_proposal_slot_secondary_required_skill UNIQUE (mission_proposal_slot_id, secondary_skill_id),
    CONSTRAINT fk_mission_proposal_slot_secondary_required_skill_slot FOREIGN KEY (mission_proposal_slot_id) REFERENCES consultant_platform.mission_proposal_slot (mission_proposal_slot_id) ON DELETE CASCADE,
    CONSTRAINT fk_mission_proposal_slot_secondary_required_skill_skill FOREIGN KEY (secondary_skill_id) REFERENCES consultant_platform.skills_secondary (secondary_skill_id),
    CONSTRAINT fk_mission_proposal_slot_sec_req_skill_comp_level FOREIGN KEY (req_competency_level_id) REFERENCES consultant_platform.competency_level_lookup (competency_level_lookup_id)
);

CREATE INDEX IF NOT EXISTS idx_mission_proposal_slot_secondary_required_skill_slot_id
    ON consultant_platform.mission_proposal_slot_secondary_required_skill (mission_proposal_slot_id);

CREATE INDEX IF NOT EXISTS idx_mission_proposal_slot_secondary_required_skill_skill_id
    ON consultant_platform.mission_proposal_slot_secondary_required_skill (secondary_skill_id);


-- consultant_platform.mission_proposal_outcome
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS consultant_platform.mission_proposal_outcome (
    mission_proposal_outcome_id BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    mission_proposal_id         BIGINT      NOT NULL,
    outcome_status                   VARCHAR(20) NOT NULL DEFAULT 'SUBMITTED',
    outcome_note                     TEXT        NOT NULL DEFAULT '',
    created_at                       TIMESTAMPTZ NOT NULL,
    updated_at                       TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (mission_proposal_outcome_id),
    CONSTRAINT uk_mission_proposal_outcome_proposal UNIQUE (mission_proposal_id),
    CONSTRAINT chk_mission_proposal_outcome_status CHECK (outcome_status IN ('SUBMITTED', 'IN_REVIEW', 'APPROVED', 'REJECTED')),
    CONSTRAINT fk_mission_proposal_outcome_proposal FOREIGN KEY (mission_proposal_id) REFERENCES consultant_platform.mission_proposal (mission_proposal_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_mission_proposal_outcome_proposal_id
    ON consultant_platform.mission_proposal_outcome (mission_proposal_id);

CREATE INDEX IF NOT EXISTS idx_mission_proposal_outcome_created_at
    ON consultant_platform.mission_proposal_outcome (created_at);

-- -------------------------------------------------------------------------
-- consultant_platform.candidate_to_slot_match
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS consultant_platform.candidate_to_slot_match (
    candidate_to_slot_match_id BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    cand_profile_id            BIGINT      NOT NULL,
    mission_slot_id       BIGINT      NOT NULL,
    match_score                INT         NOT NULL,
    match_label                VARCHAR(40) NOT NULL,
    role_matched               BOOLEAN     NOT NULL,
    work_mode_matched          BOOLEAN     NOT NULL,
    matched_skill_count        INT         NOT NULL,
    matched_skill_ids          TEXT        NOT NULL DEFAULT '',
    matched_skill_titles       TEXT        NOT NULL DEFAULT '',
    created_at                 TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (candidate_to_slot_match_id),
    CONSTRAINT uk_candidate_to_slot_match_profile_slot UNIQUE (cand_profile_id, mission_slot_id),
    CONSTRAINT chk_candidate_to_slot_match_score CHECK (match_score >= 70),
    CONSTRAINT chk_candidate_to_slot_match_label_nonblank CHECK (CHAR_LENGTH(TRIM(match_label)) > 0),
    CONSTRAINT chk_candidate_to_slot_match_skill_count CHECK (matched_skill_count >= 0),
    CONSTRAINT fk_candidate_to_slot_match_profile FOREIGN KEY (cand_profile_id) REFERENCES consultant_platform.cand_profile (cand_profile_id) ON DELETE CASCADE,
    CONSTRAINT fk_candidate_to_slot_match_slot FOREIGN KEY (mission_slot_id) REFERENCES consultant_platform.mission_slot (mission_slot_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_candidate_to_slot_match_profile_id
    ON consultant_platform.candidate_to_slot_match (cand_profile_id);

CREATE INDEX IF NOT EXISTS idx_candidate_to_slot_match_slot_id
    ON consultant_platform.candidate_to_slot_match (mission_slot_id);

CREATE INDEX IF NOT EXISTS idx_candidate_to_slot_match_score
    ON consultant_platform.candidate_to_slot_match (match_score);

CREATE INDEX IF NOT EXISTS idx_candidate_to_slot_match_created_at
    ON consultant_platform.candidate_to_slot_match (created_at);

-- -------------------------------------------------------------------------
-- consultant_platform.candidate_presentation_artifact
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS consultant_platform.candidate_presentation_artifact (
    candidate_presentation_artifact_id BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    source_candidate_to_slot_match_id  BIGINT       NOT NULL,
    cand_profile_id                    BIGINT       NOT NULL,
    mission_id                    BIGINT       NOT NULL,
    mission_slot_id               BIGINT       NOT NULL,
    artifact_status                    VARCHAR(60)  NOT NULL,
    presentation_title                 VARCHAR(255) NOT NULL,
    customer_facing_content_json       TEXT         NOT NULL DEFAULT '{}',
    ops_review_content_json            TEXT         NOT NULL DEFAULT '{}',
    evidence_trace_json                TEXT         NOT NULL DEFAULT '{}',
    created_at                         TIMESTAMPTZ  NOT NULL,
    updated_at                         TIMESTAMPTZ  NOT NULL,
    PRIMARY KEY (candidate_presentation_artifact_id),
    CONSTRAINT uk_candidate_presentation_artifact_match UNIQUE (source_candidate_to_slot_match_id),
    CONSTRAINT chk_candidate_presentation_artifact_status CHECK (artifact_status IN ('PENDING_GENERATION', 'GENERATED', 'OPS_REVIEW', 'GENERATION_FAILED')),
    CONSTRAINT chk_candidate_presentation_artifact_title_nonblank CHECK (CHAR_LENGTH(TRIM(presentation_title)) > 0),
    CONSTRAINT chk_candidate_presentation_artifact_timestamps CHECK (created_at <= updated_at),
    CONSTRAINT fk_candidate_presentation_artifact_match FOREIGN KEY (source_candidate_to_slot_match_id) REFERENCES consultant_platform.candidate_to_slot_match (candidate_to_slot_match_id) ON DELETE CASCADE,
    CONSTRAINT fk_candidate_presentation_artifact_profile FOREIGN KEY (cand_profile_id) REFERENCES consultant_platform.cand_profile (cand_profile_id) ON DELETE CASCADE,
    CONSTRAINT fk_candidate_presentation_artifact_mission FOREIGN KEY (mission_id) REFERENCES consultant_platform.mission (mission_id) ON DELETE CASCADE,
    CONSTRAINT fk_candidate_presentation_artifact_slot FOREIGN KEY (mission_slot_id) REFERENCES consultant_platform.mission_slot (mission_slot_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_candidate_presentation_artifact_profile
    ON consultant_platform.candidate_presentation_artifact (cand_profile_id);

CREATE INDEX IF NOT EXISTS idx_candidate_presentation_artifact_mission
    ON consultant_platform.candidate_presentation_artifact (mission_id);

CREATE INDEX IF NOT EXISTS idx_candidate_presentation_artifact_slot
    ON consultant_platform.candidate_presentation_artifact (mission_slot_id);

CREATE INDEX IF NOT EXISTS idx_candidate_presentation_artifact_status
    ON consultant_platform.candidate_presentation_artifact (artifact_status);

CREATE INDEX IF NOT EXISTS idx_candidate_presentation_artifact_updated_at
    ON consultant_platform.candidate_presentation_artifact (updated_at);

-- -------------------------------------------------------------------------
-- consultant_platform.match_notification_delivery
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS consultant_platform.match_notification_delivery (
    match_notification_delivery_id     BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    delivery_group_key                 VARCHAR(220) NOT NULL,
    primary_candidate_to_slot_match_id BIGINT       NOT NULL,
    candidate_to_slot_match_ids        TEXT         NOT NULL,
    cand_profile_id                    BIGINT       NOT NULL,
    mission_id                         BIGINT       NOT NULL,
    match_recorded_at                  TIMESTAMPTZ  NOT NULL,
    recipient_email                    VARCHAR(320) NOT NULL,
    sender_email                       VARCHAR(320) NOT NULL,
    subject                            VARCHAR(255) NOT NULL,
    provider                           VARCHAR(60)  NOT NULL,
    send_source                        VARCHAR(60)  NOT NULL,
    provider_message_id                VARCHAR(255) NULL,
    provider_response_ref              VARCHAR(1000) NULL,
    status                             VARCHAR(40)  NOT NULL,
    send_started_at                    TIMESTAMPTZ  NOT NULL,
    send_completed_at                  TIMESTAMPTZ  NULL,
    created_at                         TIMESTAMPTZ  NOT NULL,
    updated_at                         TIMESTAMPTZ  NOT NULL,
    PRIMARY KEY (match_notification_delivery_id),
    CONSTRAINT uk_match_notification_delivery_group_provider_recipient UNIQUE (delivery_group_key, provider, recipient_email),
    CONSTRAINT chk_match_notification_delivery_group_key_nonblank CHECK (CHAR_LENGTH(TRIM(delivery_group_key)) > 0),
    CONSTRAINT chk_match_notification_delivery_match_ids_nonblank CHECK (CHAR_LENGTH(TRIM(candidate_to_slot_match_ids)) > 0),
    CONSTRAINT chk_match_notification_delivery_recipient_has_at CHECK (recipient_email LIKE '%@%'),
    CONSTRAINT chk_match_notification_delivery_sender_has_at CHECK (sender_email LIKE '%@%'),
    CONSTRAINT chk_match_notification_delivery_subject_nonblank CHECK (CHAR_LENGTH(TRIM(subject)) > 0),
    CONSTRAINT chk_match_notification_delivery_provider_nonblank CHECK (CHAR_LENGTH(TRIM(provider)) > 0),
    CONSTRAINT chk_match_notification_delivery_send_source CHECK (send_source IN ('OPS_REST', 'PLATFORM_OPS_TOOL', 'AUTO_SEND')),
    CONSTRAINT chk_match_notification_delivery_status CHECK (status IN ('SEND_IN_PROGRESS', 'SENT', 'FAILED')),
    CONSTRAINT chk_match_notification_delivery_timestamps CHECK (created_at <= updated_at AND send_started_at <= updated_at AND (send_completed_at IS NULL OR send_started_at <= send_completed_at)),
    CONSTRAINT fk_match_notification_delivery_primary_match FOREIGN KEY (primary_candidate_to_slot_match_id) REFERENCES consultant_platform.candidate_to_slot_match (candidate_to_slot_match_id) ON DELETE CASCADE,
    CONSTRAINT fk_match_notification_delivery_profile FOREIGN KEY (cand_profile_id) REFERENCES consultant_platform.cand_profile (cand_profile_id) ON DELETE CASCADE,
    CONSTRAINT fk_match_notification_delivery_mission FOREIGN KEY (mission_id) REFERENCES consultant_platform.mission (mission_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_match_notification_delivery_group_key
    ON consultant_platform.match_notification_delivery (delivery_group_key);

CREATE INDEX IF NOT EXISTS idx_match_notification_delivery_primary_match
    ON consultant_platform.match_notification_delivery (primary_candidate_to_slot_match_id);

CREATE INDEX IF NOT EXISTS idx_match_notification_delivery_status
    ON consultant_platform.match_notification_delivery (status);

CREATE INDEX IF NOT EXISTS idx_match_notification_delivery_completed_at
    ON consultant_platform.match_notification_delivery (send_completed_at);

CREATE INDEX IF NOT EXISTS idx_match_notification_delivery_provider_message_id
    ON consultant_platform.match_notification_delivery (provider_message_id)
    WHERE provider_message_id IS NOT NULL;

-- -------------------------------------------------------------------------
-- runtime.mcp_runtime_session
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS runtime.mcp_runtime_session (
    session_id              VARCHAR(64)  NOT NULL,
    session_type            VARCHAR(64)  NOT NULL,
    session_phase           VARCHAR(64)  NOT NULL,
    session_version         BIGINT       NOT NULL,
    inactivity_ttl_seconds  BIGINT       NOT NULL,
    principal_id            VARCHAR(128) NOT NULL,
    principal_type          VARCHAR(64)  NOT NULL,
    principal_authority_id  VARCHAR(128) NOT NULL,
    operating_surface       VARCHAR(64)  NOT NULL,
    binding_source          VARCHAR(64)  NOT NULL,
    binding_stage           VARCHAR(64)  NOT NULL,
    active_tenant_id        VARCHAR(128) NULL,
    resume_capability_id    VARCHAR(256) NULL,
    created_at              TIMESTAMPTZ  NOT NULL,
    last_activity_at        TIMESTAMPTZ  NOT NULL,
    expires_at              TIMESTAMPTZ  NOT NULL,
    PRIMARY KEY (session_id),
    CONSTRAINT chk_runtime_session_version_positive CHECK (session_version > 0),
    CONSTRAINT chk_runtime_session_ttl_positive     CHECK (inactivity_ttl_seconds > 0),
    CONSTRAINT chk_runtime_session_timestamps       CHECK (created_at <= last_activity_at AND last_activity_at <= expires_at)
);

CREATE INDEX IF NOT EXISTS idx_runtime_session_expires_at
    ON runtime.mcp_runtime_session (expires_at);

CREATE INDEX IF NOT EXISTS idx_runtime_session_active_tenant_id
    ON runtime.mcp_runtime_session (active_tenant_id);

CREATE INDEX IF NOT EXISTS idx_runtime_session_principal_id
    ON runtime.mcp_runtime_session (principal_id);

CREATE UNIQUE INDEX IF NOT EXISTS uk_runtime_session_resume_capability_id
    ON runtime.mcp_runtime_session (resume_capability_id)
    WHERE resume_capability_id IS NOT NULL;

-- -------------------------------------------------------------------------
-- runtime.audit_entry
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS runtime.audit_entry (
    audit_id       BIGINT       NOT NULL GENERATED ALWAYS AS IDENTITY,
    audit_category VARCHAR(64)  NOT NULL,
    event_type     VARCHAR(128) NOT NULL,
    outcome        VARCHAR(32)  NOT NULL,
    principal_id   VARCHAR(256),
    tenant_id      VARCHAR(256),
    session_id     VARCHAR(64),
    request_id     VARCHAR(256),
    record_type    VARCHAR(64),
    record_id      BIGINT,
    detail         TEXT,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    PRIMARY KEY (audit_id)
);

CREATE INDEX IF NOT EXISTS idx_audit_principal  ON runtime.audit_entry (principal_id);
CREATE INDEX IF NOT EXISTS idx_audit_tenant     ON runtime.audit_entry (tenant_id);
CREATE INDEX IF NOT EXISTS idx_audit_session    ON runtime.audit_entry (session_id);
CREATE INDEX IF NOT EXISTS idx_audit_record     ON runtime.audit_entry (record_type, record_id);
CREATE INDEX IF NOT EXISTS idx_audit_category   ON runtime.audit_entry (audit_category);
CREATE INDEX IF NOT EXISTS idx_audit_created_at ON runtime.audit_entry (created_at);
